# Generated by Django 5.2.7 on 2025-12-26 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location_name', models.CharField(max_length=300)),
                ('start_location_latitude', models.FloatField()),
                ('start_location_longitude', models.FloatField()),
                ('completed', models.BooleanField(default=False)),
                ('walker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.walker')),
                ('wanderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.wanderer')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledWalks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walk_completed', models.BooleanField(default=False)),
                ('date', models.CharField(max_length=300)),
                ('time', models.CharField(max_length=300)),
                ('start_location_name', models.CharField(max_length=300)),
                ('start_location_latitude', models.FloatField()),
                ('start_location_longitude', models.FloatField()),
                ('payment_id', models.BigIntegerField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walks.room')),
                ('walker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.walker')),
                ('wanderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.wanderer')),
            ],
        ),
        migrations.CreateModel(
            name='LiveLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walks.room')),
            ],
            options={
                'unique_together': {('user', 'room')},
            },
        ),
    ]
