# Generated by Django 5.2.7 on 2025-10-31 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_user_is_profile_completed_user_is_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location_name', models.CharField(max_length=300)),
                ('start_location_latitude', models.FloatField()),
                ('start_location_longitude', models.FloatField()),
                ('walker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.walker')),
                ('wanderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.wanderer')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledWalks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walk_completed', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('start_location_name', models.CharField(max_length=300)),
                ('start_location_latitude', models.FloatField()),
                ('start_location_longitude', models.FloatField()),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='walks.room')),
                ('walker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.walker')),
                ('wanderer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.wanderer')),
            ],
        ),
        migrations.CreateModel(
            name='LiveLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walks.room')),
            ],
            options={
                'unique_together': {('user', 'room')},
            },
        ),
    ]
