# Generated by Django 5.2.7 on 2025-10-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledwalks',
            name='date',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='scheduledwalks',
            name='time',
            field=models.CharField(max_length=300),
        ),
    ]
