# Generated by Django 5.2.7 on 2025-10-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0002_alter_scheduledwalks_date_alter_scheduledwalks_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livelocation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livelocation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
