# Generated by Django 5.2.7 on 2025-11-01 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_is_profile_completed_user_is_verified'),
        ('walks', '0003_alter_livelocation_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledwalks',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walks.room'),
        ),
        migrations.AlterField(
            model_name='scheduledwalks',
            name='walker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.walker'),
        ),
        migrations.AlterField(
            model_name='scheduledwalks',
            name='wanderer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.wanderer'),
        ),
    ]
