# Generated by Django 5.2.7 on 2025-12-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0004_alter_scheduledwalks_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledwalks',
            name='payment_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
