# Generated by Django 5.2.7 on 2025-12-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0005_scheduledwalks_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
