# Generated by Django 5.2.7 on 2025-10-26 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_alter_walker_male'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=20)),
                ('loc_lat', models.FloatField()),
                ('loc_long', models.FloatField()),
                ('fees_paid', models.BooleanField(default=False)),
                ('payment_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('walker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_received', to='accounts.walker')),
                ('wanderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_sent', to='accounts.wanderer')),
            ],
        ),
    ]
