# Generated by Django 5.2.7 on 2025-12-26 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wanderer_name', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('walker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.walker')),
                ('wanderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.wanderer')),
            ],
        ),
        migrations.CreateModel(
            name='WandererFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walker_name', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField()),
                ('walker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.walker')),
                ('wanderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.wanderer')),
            ],
        ),
    ]
