# Generated by Django 5.2.7 on 2025-10-19 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('recent_otp', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.BigIntegerField(blank=True, null=True)),
                ('is_walker', models.BooleanField(blank=True, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WalkingPace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Walker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('about_yourself', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wanderer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WandererPreferences',
            fields=[
                ('wanderer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.wanderer')),
                ('need_mobility_assistance', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WalkerWalkingPace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walking_pace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.walkingpace')),
                ('walker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.walker')),
            ],
            options={
                'unique_together': {('walker', 'walking_pace')},
            },
        ),
        migrations.CreateModel(
            name='WalkerLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.language')),
                ('walker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.walker')),
            ],
            options={
                'unique_together': {('walker', 'language')},
            },
        ),
        migrations.CreateModel(
            name='WandererPreferenceWalkingPace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walking_pace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.walkingpace')),
                ('wanderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.wandererpreferences')),
            ],
            options={
                'unique_together': {('wanderer', 'walking_pace')},
            },
        ),
        migrations.CreateModel(
            name='WandererPreferenceLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.language')),
                ('wanderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.wandererpreferences')),
            ],
            options={
                'unique_together': {('wanderer', 'language')},
            },
        ),
        migrations.CreateModel(
            name='WandererPreferenceCharity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.charity')),
                ('wanderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.wandererpreferences')),
            ],
            options={
                'unique_together': {('wanderer', 'charity')},
            },
        ),
    ]
