# Generated by Django 5.2.7 on 2025-10-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_walker_name_walker_rating_wanderer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wanderer',
            old_name='rating',
            new_name='total_rating',
        ),
        migrations.RemoveField(
            model_name='walker',
            name='rating',
        ),
        migrations.AddField(
            model_name='walker',
            name='total_rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='walker',
            name='total_wanderer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='wanderer',
            name='total_walker',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
