# Generated by Django 5.2.7 on 2025-10-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_rating_wanderer_total_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanderer',
            name='total_rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
