# Generated by Django 5.2.7 on 2025-10-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_wanderer_total_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='walker',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walker',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='walker',
            name='is_free_plan',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='walker',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walker',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walker',
            name='male',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walker',
            name='max_walk_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wandererpreferences',
            name='female',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wandererpreferences',
            name='male',
            field=models.BooleanField(default=False),
        ),
    ]
