# Generated by Django 5.2.7 on 2025-10-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_walker_expiry_date_walker_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walker',
            name='male',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
