# Generated by Django 5.2.7 on 2025-10-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_walker_male'),
    ]

    operations = [
        migrations.AddField(
            model_name='walker',
            name='total_earning',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='walker',
            name='total_walks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wanderer',
            name='total_charity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='wanderer',
            name='total_walks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='walker',
            name='max_walk_distance',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
