# Generated by Django 5.2.7 on 2025-10-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_walker_total_earning_walker_total_walks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walker',
            name='location_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
