# Generated by Django 5.2.7 on 2025-10-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_walker_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walker',
            name='location_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
