# Generated by Django 5.2.7 on 2025-11-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_is_profile_completed_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanderer',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
