# Generated by Django 5.2.7 on 2025-12-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_wanderer_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanderer',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='walker',
            name='location_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
