# Generated by Django 5.2.7 on 2025-12-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_wanderer_photo_url_alter_walker_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
